-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: 616c1ebd1898c91de9a0548866a59cbd9f4547f6
    hooks:
    -   id: autopep8-wrapper
        language_version: python3
    -   id: check-added-large-files
    -   id: check-docstring-first
        language_version: python3
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3
    -   id: detect-private-key
        exclude: (bootstrap-scss|docs|bootstrap)$
    -   id: double-quote-string-fixer
        language_version: python3
    -   id: end-of-file-fixer
    -   id: flake8
        language_version: python3
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    sha: 2f63005157f76e34303fc891ec9e9bc97d267d4a
    hooks:
    -   id: remove-tabs
        exclude: (bootstrap-scss|docs|bootstrap|Makefile|debian/rules)$
        language_version: python2.7
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    sha: 3eb13b9647543ad4d6a62c8be8a9131e3b99b96a
    hooks:
    -   id: scss-lint
-   repo: local
    hooks:
    -   id: no-top-level-header
        language: pcre
        name: No Top-Level Headers (Markdown)
        entry: ^#\s
        files: \.md$
